services:
  backend:
    build:
      dockerfile: Dockerfile
      context: Backend/
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/calculate"]
      interval: 20s
      timeout: 30s
      retries: 5
      start_period: 30s

  frontend: 
    build: 
      dockerfile: Dockerfile
      context: Frontend/
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy