# Generated by Django 4.2.4 on 2025-07-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_research_researcher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='topic',
            field=models.CharField(max_length=100),
        ),
    ]
