# Generated by Django 4.2.4 on 2025-07-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_research_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='researcher',
            new_name='author',
        ),
    ]
