# Generated by Django 4.2.4 on 2025-07-20 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_rename_researcher_research_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research', to=settings.AUTH_USER_MODEL),
        ),
    ]
