# Generated by Django 4.2.4 on 2025-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_research_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='research_papers',
            field=models.TextField(null=True),
        ),
    ]
